### ISSUE TITLE
[BUG] Apllication crash when trying to delete copy-pasted notes on a new chart

### ISSUE THREAD

**Issue by pyrowski5** [PerryAsleep/GrooveAuthor#12]
**Bug Description**
When selecting a pasted note on a new chart and pressing DEL on a keyboard the application doesn't do anything, after trying to delete the note again application crashes.

**Steps to Reproduce**
1. Create a chart
2. Place a few notes
3. Select and copy them
4. Create another new chart
5. Paste the notes in the new chart
6. Select a note
7. Try to delete the selected note
8. Application crashes

**Expected Behavior**
Notes are being deleted

**Screenshots**
Not applicable

**Version**
v0.2.0.0
Issue also exists in v0.1.0.0

**Log**
[GrooveAuthor 2024-07-21 20-27-27.log](https://github.com/user-attachments/files/16325661/GrooveAuthor.2024-07-21.20-27-27.log)

**Comment by PerryAsleep** [comment]
Thank you for reporting this! This has been fixed in https://github.com/PerryAsleep/GrooveAuthor/commit/ab7ba92a1d32264fbcb98e641bd9e461b64b58a3. [Release 0.2.1](https://github.com/PerryAsleep/GrooveAuthor/releases/tag/v0.2.1) contains this fix.
