### ISSUE TITLE
[BUG] Units for fake regions are incorrect

### ISSUE THREAD

**Issue by MdXMaxX** [PerryAsleep/GrooveAuthor#13]
**Bug Description**
In Stepmania, fake regions are defined in units of beats.  GrooveAuthor, however, interprets the value of a fake region in units of seconds, and will incorrectly render fake regions as a result.

**Expected Behavior**
GrooveAuthor uses units of beats for fake regions.

**Screenshots**
In this example, I have a 2-beat fake region.  In Stepmania, only the mines are fakes, the tap notes are real.  But in GrooveAuthor, the fake region incorrectly extends to cover several notes.
![image](https://github.com/user-attachments/assets/0e20a79c-b08e-411f-8626-3e1e9343102c)

**Version**
0.2.1.0

**Comment by PerryAsleep** [comment]
Thank you for finding and reporting this! It should be fixed in https://github.com/PerryAsleep/GrooveAuthor/commit/05c2b5c7386240eafae2a4e877a42038dafe1d1b. I will make a new release with this bug fix sometime soon.

**Comment by PerryAsleep** [comment]
The fix for this is available in [v0.2.2](https://github.com/PerryAsleep/GrooveAuthor/releases/tag/v0.2.2).
