### ISSUE TITLE
[FEATURE REQUEST] Limitting snaps

### ISSUE THREAD

**Issue by Lisek573** [PerryAsleep/GrooveAuthor#15]
**Limitting snaps**
For songs that are on 4/4 metrum I rarely have reason to use 3/4 related arrows like 12ths, 24ths and etc. I would like to have option to toggle between 4/4 arrows (4, 8, 16, 32, 64), 3/4 arrows (4, 12, 24, 48) and all arrows (everything).

**Comment by PerryAsleep** [comment]
Hello, Thanks for these requests. Would you mind keeping this request (#15) to one feature and splitting the other two out into individual requests? That will help keep any conversation around the requests organized and it will help me track work against releases.

**Comment by Lisek573** [comment]
Np :)

**Comment by PerryAsleep** [comment]
This is now in as of https://github.com/PerryAsleep/GrooveAuthor/commit/d2f2f5a4f761642f371085a858253040d6a0262b, though the work was split over a few commits. This is in the [multiple-active-charts](https://github.com/PerryAsleep/GrooveAuthor/tree/multiple-active-charts) branch where I am doing a bunch of UI rework to support https://github.com/PerryAsleep/GrooveAuthor/issues/11, the feature request for multiple charts open simultaneously.

There is a new `Snap Limit` control. It shows the same note types as the existing `Snap` control. When a note type other than `None` is chosen as the limit then when cycling through snap levels you will be limited to those which evenly divide the limit. So in this example where the limit is 16th notes you will only cycle through None, 1/4, 1/8, and 1/16.
![snap-limit](https://github.com/user-attachments/assets/e8815027-653d-42d6-81fb-a85a36b243ea)

This will be available in the next major release that includes the multiple active chart support. I'm not sure when that will be yet.

**Comment by PerryAsleep** [comment]
This is now available in [v0.3.0](https://github.com/PerryAsleep/GrooveAuthor/releases/tag/v0.3.0).
