### ISSUE TITLE
[FEATURE REQUEST] Anonymizing files

### ISSUE THREAD

**Issue by Lisek573** [PerryAsleep/GrooveAuthor#17]
**Anonymizing files**
https://i.imgur.com/6629tMl.png
This is also related to dimocracy contest. There is a rule that requires sm/ssc files to be anonymized. Due to that, GA metadata has to be removed. Would be nice to have a checkbox that would toggle between having the metadata in file and not. Would be also nice to have option to completely anonymize file to be complaint with the requirements posted.

**Comment by PerryAsleep** [comment]
What would your expectation be for an option to completely anonymize the file? I see from that image you shared that there is an expectation that the chart description is left blank, which can be done by not adding a description. I can't tell from that image whether there is an expectation that properties be written in a specific order. If that is an expectation that is something I probably won't support now. The order of the fields does not matter and I wouldn't consider property order to be information which identifies an author. Adding custom order support would add some complexity that is currently not feeling warranted. I also see in that image there are some valid sm/ssc properties missing that GrooveAuthor writes like `LYRICSPATH` and the very useful `LASTSECONDHINT`. Right now I am resistant to the idea of removing these valid properties as doing so removes useful functionality. I also say all this just from my read on the image you shared which to me looks like the intent for these restrictions is to make so members of the competition cannot identify the author of a chart so as not to bias their opinions. I wouldn't consider the presence of properties like `LASTSECONDHINT` to be identifying information. But if there is more behind these restrictions please let me know so I can reconsider.

All that said I can see the want to specifically remove the custom data GrooveAuthor saves. I should be able to add that without too much work. But I'd like to talk through the other requests in more details.

**Comment by Lisek573** [comment]
>> I see from that image you shared that there is an expectation that the chart description is left blank, which can be done by not adding a description.

Option to one click delete all the data (stuff between : and ; ) that can identify the charter - credit (song), credit (chart), description (chart), name (chart), genre, origin, all the graphic lines include cdtitle, jacket, cdimage, discimage, lyricspath, bn and bg (song).

>> I can't tell from that image whether there is an expectation that properties be written in a specific order. If that is an expectation that is something I probably won't support now. The order of the fields does not matter and I wouldn't consider property order to be information which identifies an author.

I also think it does not matter as different editors save that data differently. 

>>  Right now I am resistant to the idea of removing these valid properties as doing so removes useful functionality.

I think the same. Leave them as is.

**Comment by PerryAsleep** [comment]
This has been added in https://github.com/PerryAsleep/GrooveAuthor/commit/c9f3d998191991973564ac0e56e17b8d0bc5f5ef and is available in [v0.2.3](https://github.com/PerryAsleep/GrooveAuthor/releases/tag/v0.2.3). There are now `Anonymize Save Data` and `Remove Custom Save Data` options under `File` > `Advanced Save Options`. `Anonymize Save Data` will ensure blank values are saved for a number of properties including the ones you listed above. `Remove Custom Save Data` will cause GrooveAuthor to not save any custom data in `sm` and `ssc` files
