### ISSUE TITLE
Minor Annoyance - User has to click "reload" once for every time the file has changed externally

### ISSUE THREAD

**Issue by sukibaby** [PerryAsleep/GrooveAuthor#19]
I'm using GrooveAuthor v0.2.1.0.

To reproduce, have a file open in GrooveAuthor as well as another editor, and do multiple saves in the external editor.

You'd expect to only click the "Reload" button once when going back to GrooveAuthor, but you actually have to confirm each individual time the program noticed a change.

https://github.com/user-attachments/assets/80c38ec4-b98b-4d4d-adff-1855da6dc42f

**Comment by PerryAsleep** [comment]
Thanks for reporting this and including the video. This has been addressed in https://github.com/PerryAsleep/GrooveAuthor/commit/a79d1c7fb08f929bc1c5a4c8322ae312a78e212e and it will be available in the next release.

**Comment by PerryAsleep** [comment]
This is now available in [v0.3.0](https://github.com/PerryAsleep/GrooveAuthor/releases/tag/v0.3.0).
