### ISSUE TITLE
Can't build Grooveauthor

### ISSUE THREAD

**Issue by compuerr** [PerryAsleep/GrooveAuthor#3]
I have Windows 11 64-bit and I installed Visual Studio Community 2022. Then I installed the latest Git 64-bit so I could run the git command to get the latest Grooveauthor. I then opened GrooveAuthor.sln in Visual Studio, 

I got the following issues and am not sure exactly what I need to do to resolve it so I can build this.
I can try to run it despite the build errors but that doesn't work.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "call C:\Users\user\GrooveAuthor\StepManiaEditor\build.bat "C:\Users\user\GrooveAuthor\StepManiaEditor\" "C:\Users\user\GrooveAuthor\StepManiaEditor\bin\Debug\net7.0-windows\"" exited with code 1.	StepManiaEditor	C:\Users\user\GrooveAuthor\StepManiaEditor\StepManiaEditor.csproj	108	
Warning	CS0067	The event 'Microphone.BufferReady' is never used	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Audio\Microphone.cs	208	Active
Warning	CS3021	'Color.Color(uint)' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Color.cs	176	Active
Warning	CS3021	'Color.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Color.cs	1791	Active
Warning	CS0618	'ModelMeshPart.ModelMeshPart()' is obsolete: 'This constructor is deprecated and will be made internal in a future release.'	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Content\ContentReaders\ModelReader.cs	131	Active
Warning	CS3021	'Game.Window' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Game.cs	351	Active
Warning	CS0067	The event 'GraphicsDevice.DeviceLost' is never used	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\GraphicsDevice.cs	142	Active
Warning	CS0067	The event 'GraphicsDevice.ResourceCreated' is never used	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\GraphicsDevice.cs	145	Active
Warning	CS0067	The event 'GraphicsDevice.ResourceDestroyed' is never used	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\GraphicsDevice.cs	146	Active
Warning	CS3021	'Alpha8.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\Alpha8.cs	20	Active
Warning	CS3021	'Bgr565.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\Bgr565.cs	47	Active
Warning	CS3021	'Bgra4444.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\Bgra4444.cs	49	Active
Warning	CS3021	'Bgra5551.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\Bgra5551.cs	19	Active
Warning	CS3021	'Byte4.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\Byte4.cs	65	Active
Warning	CS3021	'HalfSingle.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\HalfSingle.cs	19	Active
Warning	CS8981	The type name 'uif' only contains lower-cased ascii characters. Such names may become reserved for the language.	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\HalfTypeHelper.cs	13	Active
Warning	CS3021	'HalfVector2.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\HalfVector2.cs	53	Active
Warning	CS3021	'HalfVector4.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\HalfVector4.cs	79	Active
Warning	CS3021	'NormalizedByte2.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\NormalizedByte2.cs	35	Active
Warning	CS3021	'NormalizedByte4.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\NormalizedByte4.cs	35	Active
Warning	CS3021	'NormalizedShort2.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\NormalizedShort2.cs	35	Active
Warning	CS3021	'NormalizedShort4.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\NormalizedShort4.cs	35	Active
Warning	CS3021	'Rg32.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\Rg32.cs	18	Active
Warning	CS3021	'Rgba1010102.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\Rgba1010102.cs	19	Active
Warning	CS3021	'Rgba64.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\Rgba64.cs	18	Active
Warning	CS3021	'Short2.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\Short2.cs	35	Active
Warning	CS3021	'Short4.PackedValue' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PackedVector\Short4.cs	65	Active
Warning	CS0169	The field 'PresentationParameters.disposed' is never used	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\PresentationParameters.cs	34	Active
Warning	CS0067	The event 'RenderTargetCube.ContentLost' is never used	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Graphics\RenderTargetCube.cs	45	Active
Warning	CS3021	'SoundEffect.Speakers' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Platform\Audio\SoundEffect.XAudio.cs	31	Active
Warning	CS3021	'RenderTargetCube.GetRenderTargetView(int)' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Platform\Graphics\RenderTargetCube.DirectX.cs	89	Active
Warning	CS3021	'RenderTargetCube.GetDepthStencilView()' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Platform\Graphics\RenderTargetCube.DirectX.cs	96	Active
Warning	NETSDK1137	It is no longer necessary to use the Microsoft.NET.Sdk.WindowsDesktop SDK. Consider changing the Sdk attribute of the root Project element to 'Microsoft.NET.Sdk'.	MonoGame.Framework.WindowsDX	C:\Program Files\dotnet\sdk\8.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets	148	
Warning	SYSLIB0003	'PermissionSetAttribute' is obsolete: 'Code Access Security is not supported or honored by the runtime.' (https://aka.ms/dotnet-warnings/SYSLIB0003)	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Platform\Windows\WinFormsGameForm.cs	77	
Warning	SYSLIB0003	'SecurityAction' is obsolete: 'Code Access Security is not supported or honored by the runtime.' (https://aka.ms/dotnet-warnings/SYSLIB0003)	MonoGame.Framework.WindowsDX	C:\Users\user\GrooveAuthor\StepManiaEditor\MonoGame\MonoGame.Framework\Platform\Windows\WinFormsGameForm.cs	77	

```

**Comment by compuerr** [comment]
The debug output

`'GrooveAuthor.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Lil wow\GrooveAuthor\StepManiaEditor\bin\Debug\net7.0-windows\GrooveAuthor.dll'. Symbols loaded.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\hotreload\Microsoft.Extensions.DotNetDeltaApplier.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.IO.Pipes.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Threading.Overlapped.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Security.AccessControl.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Security.Principal.Windows.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Security.Claims.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Runtime.Loader.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Lil wow\GrooveAuthor\StepManiaEditor\bin\Debug\net7.0-windows\MonoGame.Framework.dll'. Symbols loaded.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Lil wow\GrooveAuthor\StepManiaEditor\bin\Debug\net7.0-windows\Fumen.dll'. Symbols loaded.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Lil wow\GrooveAuthor\StepManiaEditor\bin\Debug\net7.0-windows\ImGui.NET.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Lil wow\GrooveAuthor\StepManiaEditor\bin\Debug\net7.0-windows\StepManiaLibrary.dll'. Symbols loaded.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.16\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.16\System.Windows.Forms.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Drawing.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.ComponentModel.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Collections.Specialized.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.ComponentModel.TypeConverter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.16\System.Drawing.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Diagnostics.TraceSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\Microsoft.Win32.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.ComponentModel.EventBasedAsync.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Threading.Thread.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.16\Accessibility.dll'. Module was built without symbols.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.16\Microsoft.Win32.SystemEvents.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Lil wow\GrooveAuthor\StepManiaEditor\bin\Debug\net7.0-windows\SharpDX.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Text.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.DllNotFoundException' in GrooveAuthor.dll
An unhandled exception of type 'System.DllNotFoundException' occurred in GrooveAuthor.dll
Unable to load DLL 'fmod' or one of its dependencies: The specified module could not be found. (0x8007007E)

'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread '[Thread Destroyed]' (20496) has exited with code 0 (0x0).
The thread '[Thread Destroyed]' (19652) has exited with code 0 (0x0).
The thread '[Thread Destroyed]' (20500) has exited with code 0 (0x0).
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GrooveAuthor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\System.Text.Encoding.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[19904] GrooveAuthor.exe' has exited with code 0 (0x0).
`

**Comment by PerryAsleep** [comment]
Hello. Thanks for your interest in building the project.

It looks like you are missing the submodule projects. From within your `GrooveAuthor` directory try running `git submodule update --init --recursive`. That should populate the following folders:
- `StepManiaEditor\MonoGame`
- `StepManiaLibrary`
- `StepManiaLibrary\Fumen`

**Comment by compuerr** [comment]
> Hello. Thanks for your interest in building the project.
> 
> It looks like you are missing the submodule projects. From within your `GrooveAuthor` directory try running `git submodule update --init --recursive`. That should populate the following folders:
> 
> * `StepManiaEditor\MonoGame`
> * `StepManiaLibrary`
> * `StepManiaLibrary\Fumen`

Thank you for the reply!
That was not the issue after all, looking further into the build error I noticed something preventing building from happening correctly when the user home directory has a space in it, so i'll be submitting the needed fix which allowed me to build Grooveauthor. :)

![Screenshot 2024-03-12 043122](https://github.com/PerryAsleep/GrooveAuthor/assets/163092272/145976f1-a6fa-49c0-a957-40d6629e3d74)

**Comment by PerryAsleep** [comment]
Haha, excellent. Thanks for the PR. It's been merged in.
